Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,7 +12,15 @@ jobs:
       - run: mkdir sanity;
       - run: jmeter -n -t Demosix_Prod_Demo_steps.jmx -l sanity/Demosix_Prod_Demo_steps_test.jtl -e -o sanity/Demosix_Prod_Demo -j sanity/jmeter.log
       - run: ls -l
-      - run: echo [$(grep false sanity/Demosix_Prod_Demo_steps_test.jtl | wc -l)] < "0"   
+      - run: |
+             if [ $(grep false sanity/Demosix_Prod_Demo_steps_test.jtl | wc -l) -lt "0" ]; then
+               echo "pass"
+               exit 0
+             else 
+               echo "fail"
+               exit 1
+             fi
+      # run: echo [$(grep false sanity/Demosix_Prod_Demo_steps_test.jtl | wc -l)] < "0"   
       # run: jmeter -n -t Staging_Appinsight_summery_full.jmx -l /sanity/Staging_Summary_Test2.jtl -e -o /sanity/StagingSummary_Test2
       # run: jmeter -n -t Sonrai_PCAPIAPIs.jmx -l /sanity/PCAPI_TestResult.jtl -e -o /sanity/PCAPI_1
       # run: jmeter -n -t Sonrai_Graphql_staging.jmx -l /tmp/artifacts/runResults4.jtl -e -o /sanity/result2
@@ -21,11 +29,12 @@ jobs:
       - slack/notify:
          channel: performance-test
          event: fail
-         mentions: 'In View Job,got to Artificats folder and select .html file'
+         mentions: 'To view Result - In View Job,got to Artificats folder and select index.html file'
          template: basic_fail_1
       - slack/notify:
           channel: performance-test
           event: pass
+          mentions: 'To view Result - In View Job,got to Artificats folder and select index.html file'
           template: basic_success_1
 
 # Orchestrate our job run sequence
